allowBuilds:
  electron: true
  # This package only creates Windows installers and is not used for the macOS app.
  electron-winstaller: false
  esbuild: true
  protobufjs: true

patchedDependencies:
  openwakeword-wasm-browser@0.1.1: patches/openwakeword-wasm-browser@0.1.1.patch
