export const modelConfig = {
  helmetModelFile: 'model.high.glb',
  rotationX: 0,
  rotationY: 0,
  rotationZ: 0,
  heightScale: 0.92,
  trimTopFraction: 0.12,
  chinCenterDrop: 0.18,
  chinFlatFraction: 0.34,
  focusPadding: 1.12,
  bottomFadeHeight: 0.06,
  assembleDuration: 2600,
  assembleSpread: 2.5,
  assembleDelay: 0.38,
  assemblePieceCount: 63,
  assembleFlash: 2.5,
  particleCount: 40000,
  particleDelay: 0.3,
  particleMinSize: 6,
  particleMaxSize: 24,
  particleSpread: 1.4,
  particleEdgeOverscan: 1.22,
  particleRedColor: 0xff3b30,
  particleYellowColor: 0xffc107,
  particleWhiteColor: 0xfff7e6,
  particleWhiteRatio: 0.1,
  faceplateMaterial: 'Mat.2',
  faceplateMetalness: 1,
  faceplateRoughness: 0.36,
  faceplateClearcoatRoughness: 0.2,
  faceplateNormalSmoothingIterations: 6,
  faceplateNormalSmoothingStrength: 0.68,
  emissiveMaterialNames: [
    'PaletteMaterial001',
    'PaletteMaterial002',
    'PaletteMaterial003',
    'OpenSourceCyberPinkDetails',
    'OpenSourceCyberCyanDetails'
  ],
  primaryEmissiveMaterial: 'PaletteMaterial001',
  primaryEmissiveMultiplier: 3.2,
  eyeCoreColor: 0xe8ffff,
  eyeGlowColor: 0x00a2ff,
  emissiveColor: 0x8fefff
};
